// Auto-generated by scripts/recipe-content-engine.mjs. Do not edit by hand.
export type RecipeContentItem = {
  id: string;
  title: string;
  slug: string;
  flavorId: string;
  flavorName: string;
  flavorUrl: string;
  category: string;
  categoryLabel: string;
  time: string;
  serves: string;
  difficulty: string;
  hook: string;
  description: string;
  ingredients: string[];
  steps: string[];
  tags: string[];
  seoTitle: string;
  metaDescription: string;
};

export type RecipeSocialPost = {
  id: string;
  channel: string;
  recipeId: string;
  flavorName: string;
  hook: string;
  caption: string;
  shotList: string[];
  hashtags: string[];
};

export type RecipeBlogPost = {
  slug: string;
  title: string;
  description: string;
  recipes: string[];
  body: string;
};

export type RecipeEmailCampaign = {
  id: string;
  flavorName: string;
  subject: string;
  previewText: string;
  sections: Array<{ headline: string; body: string }>;
  ctaLabel: string;
  ctaUrl: string;
};

export const RECIPE_CONTENT_GENERATED_AT = "2026-05-24T12:20:04.924Z";
export const RECIPE_FLAVORS = [
  {
    "id": "original",
    "name": "Original",
    "productUrl": "/product/original-ramen",
    "profile": "deep soy, garlic, ginger, sesame, and balanced umami",
    "angle": "the all-purpose bottle",
    "color": "Umami"
  },
  {
    "id": "spicy-tokyo",
    "name": "Spicy Tokyo",
    "productUrl": "/product/spicy-tokyo",
    "profile": "roasted chili heat, dark soy depth, garlic, and sesame",
    "angle": "the heat-forward bottle",
    "color": "Heat"
  },
  {
    "id": "citrus-shoyu",
    "name": "Citrus Shoyu",
    "productUrl": "/product/citrus-shoyu",
    "profile": "bright citrus, clean shoyu, light heat, and a crisp finish",
    "angle": "the bright bottle",
    "color": "Bright"
  },
  {
    "id": "shoyu-reserve",
    "name": "Shoyu Reserve",
    "productUrl": "/product/shoyu-reserve",
    "profile": "slow-brewed shoyu depth, mellow salt, and savory finish",
    "angle": "the finishing and marinade bottle",
    "color": "Reserve"
  }
] as const;
export const RECIPE_USE_CASES = [
  {
    "id": "ramen",
    "label": "Ramen"
  },
  {
    "id": "rice-bowl",
    "label": "Rice Bowls"
  },
  {
    "id": "wings",
    "label": "Wings"
  },
  {
    "id": "marinade",
    "label": "Marinades"
  },
  {
    "id": "stir-fry",
    "label": "Stir Fry"
  },
  {
    "id": "dipping-sauce",
    "label": "Dipping Sauces"
  }
] as const;
export const GENERATED_RECIPES = [
  {
    "id": "original-weeknight-ramen-bowl",
    "title": "Original Weeknight Ramen Bowl",
    "slug": "original-weeknight-ramen-bowl",
    "flavorId": "original",
    "flavorName": "Original",
    "flavorUrl": "/product/original-ramen",
    "category": "ramen",
    "categoryLabel": "Ramen",
    "time": "10 min",
    "serves": "1",
    "difficulty": "Fast",
    "hook": "Turn a plain pack into a real bowl. Original brings deep soy, garlic, ginger, sesame, and balanced umami.",
    "description": "Original Weeknight Ramen Bowl turns ramen noodles into a high-crave NoodleBomb use case with the all-purpose bottle.",
    "ingredients": [
      "1 serving ramen noodles",
      "3-4 tbsp NoodleBomb",
      "soft egg",
      "scallions",
      "corn",
      "sesame"
    ],
    "steps": [
      "Cook noodles until springy, then drain or move into a hot bowl with a little broth.",
      "Add Original and toss until the noodles are glossy.",
      "Add toppings while everything is still hot.",
      "Finish with Original so the deep soy, garlic, ginger, sesame, and balanced umami comes through."
    ],
    "tags": [
      "Original",
      "Ramen",
      "Umami",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Original Weeknight Ramen Bowl | NoodleBomb Ramen",
    "metaDescription": "Original Weeknight Ramen Bowl made with NoodleBomb Original. Fast ramen idea with bold flavor and simple steps."
  },
  {
    "id": "original-crispy-chicken-rice-bowl",
    "title": "Original Crispy Chicken Rice Bowl",
    "slug": "original-crispy-chicken-rice-bowl",
    "flavorId": "original",
    "flavorName": "Original",
    "flavorUrl": "/product/original-ramen",
    "category": "rice-bowl",
    "categoryLabel": "Rice Bowls",
    "time": "18 min",
    "serves": "2",
    "difficulty": "Fast",
    "hook": "Build a bowl that tastes planned. Original brings deep soy, garlic, ginger, sesame, and balanced umami.",
    "description": "Original Crispy Chicken Rice Bowl turns warm rice into a high-crave NoodleBomb use case with the all-purpose bottle.",
    "ingredients": [
      "2 cups warm rice",
      "3-4 tbsp NoodleBomb",
      "crispy chicken",
      "cucumber",
      "sesame rice",
      "scallions"
    ],
    "steps": [
      "Start with hot rice and one crisp or seared protein.",
      "Add one fresh crunch topping and one rich topping.",
      "Spoon Original over the center and fold lightly before eating.",
      "Add extra sauce at the table if the bowl needs more punch."
    ],
    "tags": [
      "Original",
      "Rice Bowls",
      "Umami",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Original Crispy Chicken Rice Bowl | NoodleBomb Rice Bowls",
    "metaDescription": "Original Crispy Chicken Rice Bowl made with NoodleBomb Original. Fast rice bowls idea with bold flavor and simple steps."
  },
  {
    "id": "original-sticky-sesame-wings",
    "title": "Original Sticky Sesame Wings",
    "slug": "original-sticky-sesame-wings",
    "flavorId": "original",
    "flavorName": "Original",
    "flavorUrl": "/product/original-ramen",
    "category": "wings",
    "categoryLabel": "Wings",
    "time": "45 min",
    "serves": "4",
    "difficulty": "Easy",
    "hook": "Coat crispy wings without making them soggy. Original brings deep soy, garlic, ginger, sesame, and balanced umami.",
    "description": "Original Sticky Sesame Wings turns crispy wings into a high-crave NoodleBomb use case with the all-purpose bottle.",
    "ingredients": [
      "2 lb chicken wings",
      "3-4 tbsp NoodleBomb",
      "butter",
      "honey",
      "toasted sesame"
    ],
    "steps": [
      "Bake or air-fry wings at 400 F until crisp.",
      "Warm Original with butter or honey in a small pan.",
      "Toss hot wings with the sauce in a large bowl.",
      "Rest 2 minutes so the coating sets before serving."
    ],
    "tags": [
      "Original",
      "Wings",
      "Umami",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Original Sticky Sesame Wings | NoodleBomb Wings",
    "metaDescription": "Original Sticky Sesame Wings made with NoodleBomb Original. Fast wings idea with bold flavor and simple steps."
  },
  {
    "id": "original-garlic-chicken-marinade",
    "title": "Original Garlic Chicken Marinade",
    "slug": "original-garlic-chicken-marinade",
    "flavorId": "original",
    "flavorName": "Original",
    "flavorUrl": "/product/original-ramen",
    "category": "marinade",
    "categoryLabel": "Marinades",
    "time": "25 min + marinate",
    "serves": "2",
    "difficulty": "Easy",
    "hook": "Use the sauce as the backbone of a fast marinade. Original brings deep soy, garlic, ginger, sesame, and balanced umami.",
    "description": "Original Garlic Chicken Marinade turns chicken, steak, tofu, or salmon into a high-crave NoodleBomb use case with the all-purpose bottle.",
    "ingredients": [
      "1 lb chicken thighs",
      "1/3 cup NoodleBomb",
      "ginger",
      "garlic",
      "brown sugar"
    ],
    "steps": [
      "Whisk Original with oil and aromatics.",
      "Coat the protein and marinate 20 minutes to overnight depending on thickness.",
      "Cook hot and fast until browned.",
      "Rest, slice, then spoon a little fresh sauce over the top."
    ],
    "tags": [
      "Original",
      "Marinades",
      "Umami",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Original Garlic Chicken Marinade | NoodleBomb Marinades",
    "metaDescription": "Original Garlic Chicken Marinade made with NoodleBomb Original. Fast marinades idea with bold flavor and simple steps."
  },
  {
    "id": "original-broccoli-noodle-stir-fry",
    "title": "Original Broccoli Noodle Stir Fry",
    "slug": "original-broccoli-noodle-stir-fry",
    "flavorId": "original",
    "flavorName": "Original",
    "flavorUrl": "/product/original-ramen",
    "category": "stir-fry",
    "categoryLabel": "Stir Fry",
    "time": "15 min",
    "serves": "2",
    "difficulty": "Fast",
    "hook": "Finish hot food with layered flavor. Original brings deep soy, garlic, ginger, sesame, and balanced umami.",
    "description": "Original Broccoli Noodle Stir Fry turns vegetables, noodles, or rice into a high-crave NoodleBomb use case with the all-purpose bottle.",
    "ingredients": [
      "2 cups vegetables, noodles, or rice",
      "3-4 tbsp NoodleBomb",
      "broccoli",
      "mushrooms",
      "snap peas",
      "noodles"
    ],
    "steps": [
      "Cook vegetables or protein first over high heat.",
      "Add noodles or rice and toss until hot.",
      "Turn off the heat, add Original, and toss hard for 20 seconds.",
      "Serve immediately with scallions or sesame."
    ],
    "tags": [
      "Original",
      "Stir Fry",
      "Umami",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Original Broccoli Noodle Stir Fry | NoodleBomb Stir Fry",
    "metaDescription": "Original Broccoli Noodle Stir Fry made with NoodleBomb Original. Fast stir fry idea with bold flavor and simple steps."
  },
  {
    "id": "original-dumpling-dip",
    "title": "Original Dumpling Dip",
    "slug": "original-dumpling-dip",
    "flavorId": "original",
    "flavorName": "Original",
    "flavorUrl": "/product/original-ramen",
    "category": "dipping-sauce",
    "categoryLabel": "Dipping Sauces",
    "time": "3 min",
    "serves": "4",
    "difficulty": "Fast",
    "hook": "Make the dip people remember. Original brings deep soy, garlic, ginger, sesame, and balanced umami.",
    "description": "Original Dumpling Dip turns dumplings, spring rolls, fries, or vegetables into a high-crave NoodleBomb use case with the all-purpose bottle.",
    "ingredients": [
      "1/4 cup NoodleBomb",
      "rice vinegar",
      "sesame oil",
      "scallions"
    ],
    "steps": [
      "Whisk Original with vinegar or sesame oil.",
      "Taste and adjust with lime, scallion, or chili crisp.",
      "Serve in a small bowl next to hot dumplings, rolls, fries, or grilled meat.",
      "Keep extra nearby because the first bowl goes fast."
    ],
    "tags": [
      "Original",
      "Dipping Sauces",
      "Umami",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Original Dumpling Dip | NoodleBomb Dipping Sauces",
    "metaDescription": "Original Dumpling Dip made with NoodleBomb Original. Fast dipping sauces idea with bold flavor and simple steps."
  },
  {
    "id": "spicy-tokyo-fire-ramen",
    "title": "Spicy Tokyo Fire Ramen",
    "slug": "spicy-tokyo-fire-ramen",
    "flavorId": "spicy-tokyo",
    "flavorName": "Spicy Tokyo",
    "flavorUrl": "/product/spicy-tokyo",
    "category": "ramen",
    "categoryLabel": "Ramen",
    "time": "10 min",
    "serves": "1",
    "difficulty": "Fast",
    "hook": "Turn a plain pack into a real bowl. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame.",
    "description": "Spicy Tokyo Fire Ramen turns ramen noodles into a high-crave NoodleBomb use case with the heat-forward bottle.",
    "ingredients": [
      "1 serving ramen noodles",
      "3-4 tbsp NoodleBomb",
      "ground pork",
      "chili oil",
      "scallions",
      "nori"
    ],
    "steps": [
      "Cook noodles until springy, then drain or move into a hot bowl with a little broth.",
      "Add Spicy Tokyo and toss until the noodles are glossy.",
      "Add toppings while everything is still hot.",
      "Finish with Spicy Tokyo so the roasted chili heat, dark soy depth, garlic, and sesame comes through."
    ],
    "tags": [
      "Spicy Tokyo",
      "Ramen",
      "Heat",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Spicy Tokyo Fire Ramen | NoodleBomb Ramen",
    "metaDescription": "Spicy Tokyo Fire Ramen made with NoodleBomb Spicy Tokyo. Fast ramen idea with bold flavor and simple steps."
  },
  {
    "id": "spicy-tokyo-steak-rice-bowl",
    "title": "Spicy Tokyo Steak Rice Bowl",
    "slug": "spicy-tokyo-steak-rice-bowl",
    "flavorId": "spicy-tokyo",
    "flavorName": "Spicy Tokyo",
    "flavorUrl": "/product/spicy-tokyo",
    "category": "rice-bowl",
    "categoryLabel": "Rice Bowls",
    "time": "18 min",
    "serves": "2",
    "difficulty": "Fast",
    "hook": "Build a bowl that tastes planned. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame.",
    "description": "Spicy Tokyo Steak Rice Bowl turns warm rice into a high-crave NoodleBomb use case with the heat-forward bottle.",
    "ingredients": [
      "2 cups warm rice",
      "3-4 tbsp NoodleBomb",
      "steak",
      "kimchi",
      "cucumber",
      "fried egg"
    ],
    "steps": [
      "Start with hot rice and one crisp or seared protein.",
      "Add one fresh crunch topping and one rich topping.",
      "Spoon Spicy Tokyo over the center and fold lightly before eating.",
      "Add extra sauce at the table if the bowl needs more punch."
    ],
    "tags": [
      "Spicy Tokyo",
      "Rice Bowls",
      "Heat",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Spicy Tokyo Steak Rice Bowl | NoodleBomb Rice Bowls",
    "metaDescription": "Spicy Tokyo Steak Rice Bowl made with NoodleBomb Spicy Tokyo. Fast rice bowls idea with bold flavor and simple steps."
  },
  {
    "id": "spicy-tokyo-chili-wings",
    "title": "Spicy Tokyo Chili Wings",
    "slug": "spicy-tokyo-chili-wings",
    "flavorId": "spicy-tokyo",
    "flavorName": "Spicy Tokyo",
    "flavorUrl": "/product/spicy-tokyo",
    "category": "wings",
    "categoryLabel": "Wings",
    "time": "45 min",
    "serves": "4",
    "difficulty": "Easy",
    "hook": "Coat crispy wings without making them soggy. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame.",
    "description": "Spicy Tokyo Chili Wings turns crispy wings into a high-crave NoodleBomb use case with the heat-forward bottle.",
    "ingredients": [
      "2 lb chicken wings",
      "3-4 tbsp NoodleBomb",
      "butter",
      "lime",
      "chili crisp"
    ],
    "steps": [
      "Bake or air-fry wings at 400 F until crisp.",
      "Warm Spicy Tokyo with butter or honey in a small pan.",
      "Toss hot wings with the sauce in a large bowl.",
      "Rest 2 minutes so the coating sets before serving."
    ],
    "tags": [
      "Spicy Tokyo",
      "Wings",
      "Heat",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Spicy Tokyo Chili Wings | NoodleBomb Wings",
    "metaDescription": "Spicy Tokyo Chili Wings made with NoodleBomb Spicy Tokyo. Fast wings idea with bold flavor and simple steps."
  },
  {
    "id": "spicy-tokyo-steak-marinade",
    "title": "Spicy Tokyo Steak Marinade",
    "slug": "spicy-tokyo-steak-marinade",
    "flavorId": "spicy-tokyo",
    "flavorName": "Spicy Tokyo",
    "flavorUrl": "/product/spicy-tokyo",
    "category": "marinade",
    "categoryLabel": "Marinades",
    "time": "25 min + marinate",
    "serves": "2",
    "difficulty": "Easy",
    "hook": "Use the sauce as the backbone of a fast marinade. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame.",
    "description": "Spicy Tokyo Steak Marinade turns chicken, steak, tofu, or salmon into a high-crave NoodleBomb use case with the heat-forward bottle.",
    "ingredients": [
      "1 lb flank steak",
      "1/3 cup NoodleBomb",
      "garlic",
      "sesame oil",
      "lime"
    ],
    "steps": [
      "Whisk Spicy Tokyo with oil and aromatics.",
      "Coat the protein and marinate 20 minutes to overnight depending on thickness.",
      "Cook hot and fast until browned.",
      "Rest, slice, then spoon a little fresh sauce over the top."
    ],
    "tags": [
      "Spicy Tokyo",
      "Marinades",
      "Heat",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Spicy Tokyo Steak Marinade | NoodleBomb Marinades",
    "metaDescription": "Spicy Tokyo Steak Marinade made with NoodleBomb Spicy Tokyo. Fast marinades idea with bold flavor and simple steps."
  },
  {
    "id": "spicy-tokyo-udon-stir-fry",
    "title": "Spicy Tokyo Udon Stir Fry",
    "slug": "spicy-tokyo-udon-stir-fry",
    "flavorId": "spicy-tokyo",
    "flavorName": "Spicy Tokyo",
    "flavorUrl": "/product/spicy-tokyo",
    "category": "stir-fry",
    "categoryLabel": "Stir Fry",
    "time": "15 min",
    "serves": "2",
    "difficulty": "Fast",
    "hook": "Finish hot food with layered flavor. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame.",
    "description": "Spicy Tokyo Udon Stir Fry turns vegetables, noodles, or rice into a high-crave NoodleBomb use case with the heat-forward bottle.",
    "ingredients": [
      "2 cups vegetables, noodles, or rice",
      "3-4 tbsp NoodleBomb",
      "udon",
      "bok choy",
      "pork",
      "garlic"
    ],
    "steps": [
      "Cook vegetables or protein first over high heat.",
      "Add noodles or rice and toss until hot.",
      "Turn off the heat, add Spicy Tokyo, and toss hard for 20 seconds.",
      "Serve immediately with scallions or sesame."
    ],
    "tags": [
      "Spicy Tokyo",
      "Stir Fry",
      "Heat",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Spicy Tokyo Udon Stir Fry | NoodleBomb Stir Fry",
    "metaDescription": "Spicy Tokyo Udon Stir Fry made with NoodleBomb Spicy Tokyo. Fast stir fry idea with bold flavor and simple steps."
  },
  {
    "id": "spicy-tokyo-gyoza-dip",
    "title": "Spicy Tokyo Gyoza Dip",
    "slug": "spicy-tokyo-gyoza-dip",
    "flavorId": "spicy-tokyo",
    "flavorName": "Spicy Tokyo",
    "flavorUrl": "/product/spicy-tokyo",
    "category": "dipping-sauce",
    "categoryLabel": "Dipping Sauces",
    "time": "3 min",
    "serves": "4",
    "difficulty": "Fast",
    "hook": "Make the dip people remember. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame.",
    "description": "Spicy Tokyo Gyoza Dip turns dumplings, spring rolls, fries, or vegetables into a high-crave NoodleBomb use case with the heat-forward bottle.",
    "ingredients": [
      "1/4 cup NoodleBomb",
      "rice vinegar",
      "chili crisp",
      "sesame oil"
    ],
    "steps": [
      "Whisk Spicy Tokyo with vinegar or sesame oil.",
      "Taste and adjust with lime, scallion, or chili crisp.",
      "Serve in a small bowl next to hot dumplings, rolls, fries, or grilled meat.",
      "Keep extra nearby because the first bowl goes fast."
    ],
    "tags": [
      "Spicy Tokyo",
      "Dipping Sauces",
      "Heat",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Spicy Tokyo Gyoza Dip | NoodleBomb Dipping Sauces",
    "metaDescription": "Spicy Tokyo Gyoza Dip made with NoodleBomb Spicy Tokyo. Fast dipping sauces idea with bold flavor and simple steps."
  },
  {
    "id": "citrus-shoyu-cold-noodle-bowl",
    "title": "Citrus Shoyu Cold Noodle Bowl",
    "slug": "citrus-shoyu-cold-noodle-bowl",
    "flavorId": "citrus-shoyu",
    "flavorName": "Citrus Shoyu",
    "flavorUrl": "/product/citrus-shoyu",
    "category": "ramen",
    "categoryLabel": "Ramen",
    "time": "10 min",
    "serves": "1",
    "difficulty": "Fast",
    "hook": "Turn a plain pack into a real bowl. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish.",
    "description": "Citrus Shoyu Cold Noodle Bowl turns ramen noodles into a high-crave NoodleBomb use case with the bright bottle.",
    "ingredients": [
      "1 serving ramen noodles",
      "3-4 tbsp NoodleBomb",
      "cold noodles",
      "cucumber",
      "edamame",
      "sesame"
    ],
    "steps": [
      "Cook noodles until springy, then drain or move into a hot bowl with a little broth.",
      "Add Citrus Shoyu and toss until the noodles are glossy.",
      "Add toppings while everything is still hot.",
      "Finish with Citrus Shoyu so the bright citrus, clean shoyu, light heat, and a crisp finish comes through."
    ],
    "tags": [
      "Citrus Shoyu",
      "Ramen",
      "Bright",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Citrus Shoyu Cold Noodle Bowl | NoodleBomb Ramen",
    "metaDescription": "Citrus Shoyu Cold Noodle Bowl made with NoodleBomb Citrus Shoyu. Fast ramen idea with bold flavor and simple steps."
  },
  {
    "id": "citrus-shoyu-salmon-rice-bowl",
    "title": "Citrus Shoyu Salmon Rice Bowl",
    "slug": "citrus-shoyu-salmon-rice-bowl",
    "flavorId": "citrus-shoyu",
    "flavorName": "Citrus Shoyu",
    "flavorUrl": "/product/citrus-shoyu",
    "category": "rice-bowl",
    "categoryLabel": "Rice Bowls",
    "time": "18 min",
    "serves": "2",
    "difficulty": "Fast",
    "hook": "Build a bowl that tastes planned. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish.",
    "description": "Citrus Shoyu Salmon Rice Bowl turns warm rice into a high-crave NoodleBomb use case with the bright bottle.",
    "ingredients": [
      "2 cups warm rice",
      "3-4 tbsp NoodleBomb",
      "salmon",
      "avocado",
      "cucumber",
      "furikake"
    ],
    "steps": [
      "Start with hot rice and one crisp or seared protein.",
      "Add one fresh crunch topping and one rich topping.",
      "Spoon Citrus Shoyu over the center and fold lightly before eating.",
      "Add extra sauce at the table if the bowl needs more punch."
    ],
    "tags": [
      "Citrus Shoyu",
      "Rice Bowls",
      "Bright",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Citrus Shoyu Salmon Rice Bowl | NoodleBomb Rice Bowls",
    "metaDescription": "Citrus Shoyu Salmon Rice Bowl made with NoodleBomb Citrus Shoyu. Fast rice bowls idea with bold flavor and simple steps."
  },
  {
    "id": "citrus-shoyu-honey-wings",
    "title": "Citrus Shoyu Honey Wings",
    "slug": "citrus-shoyu-honey-wings",
    "flavorId": "citrus-shoyu",
    "flavorName": "Citrus Shoyu",
    "flavorUrl": "/product/citrus-shoyu",
    "category": "wings",
    "categoryLabel": "Wings",
    "time": "45 min",
    "serves": "4",
    "difficulty": "Easy",
    "hook": "Coat crispy wings without making them soggy. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish.",
    "description": "Citrus Shoyu Honey Wings turns crispy wings into a high-crave NoodleBomb use case with the bright bottle.",
    "ingredients": [
      "2 lb chicken wings",
      "3-4 tbsp NoodleBomb",
      "lime",
      "honey",
      "sesame seeds"
    ],
    "steps": [
      "Bake or air-fry wings at 400 F until crisp.",
      "Warm Citrus Shoyu with butter or honey in a small pan.",
      "Toss hot wings with the sauce in a large bowl.",
      "Rest 2 minutes so the coating sets before serving."
    ],
    "tags": [
      "Citrus Shoyu",
      "Wings",
      "Bright",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Citrus Shoyu Honey Wings | NoodleBomb Wings",
    "metaDescription": "Citrus Shoyu Honey Wings made with NoodleBomb Citrus Shoyu. Fast wings idea with bold flavor and simple steps."
  },
  {
    "id": "citrus-shoyu-salmon-marinade",
    "title": "Citrus Shoyu Salmon Marinade",
    "slug": "citrus-shoyu-salmon-marinade",
    "flavorId": "citrus-shoyu",
    "flavorName": "Citrus Shoyu",
    "flavorUrl": "/product/citrus-shoyu",
    "category": "marinade",
    "categoryLabel": "Marinades",
    "time": "25 min + marinate",
    "serves": "2",
    "difficulty": "Easy",
    "hook": "Use the sauce as the backbone of a fast marinade. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish.",
    "description": "Citrus Shoyu Salmon Marinade turns chicken, steak, tofu, or salmon into a high-crave NoodleBomb use case with the bright bottle.",
    "ingredients": [
      "1 lb salmon",
      "1/3 cup NoodleBomb",
      "ginger",
      "orange",
      "green onion"
    ],
    "steps": [
      "Whisk Citrus Shoyu with oil and aromatics.",
      "Coat the protein and marinate 20 minutes to overnight depending on thickness.",
      "Cook hot and fast until browned.",
      "Rest, slice, then spoon a little fresh sauce over the top."
    ],
    "tags": [
      "Citrus Shoyu",
      "Marinades",
      "Bright",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Citrus Shoyu Salmon Marinade | NoodleBomb Marinades",
    "metaDescription": "Citrus Shoyu Salmon Marinade made with NoodleBomb Citrus Shoyu. Fast marinades idea with bold flavor and simple steps."
  },
  {
    "id": "citrus-shoyu-shrimp-stir-fry",
    "title": "Citrus Shoyu Shrimp Stir Fry",
    "slug": "citrus-shoyu-shrimp-stir-fry",
    "flavorId": "citrus-shoyu",
    "flavorName": "Citrus Shoyu",
    "flavorUrl": "/product/citrus-shoyu",
    "category": "stir-fry",
    "categoryLabel": "Stir Fry",
    "time": "15 min",
    "serves": "2",
    "difficulty": "Fast",
    "hook": "Finish hot food with layered flavor. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish.",
    "description": "Citrus Shoyu Shrimp Stir Fry turns vegetables, noodles, or rice into a high-crave NoodleBomb use case with the bright bottle.",
    "ingredients": [
      "2 cups vegetables, noodles, or rice",
      "3-4 tbsp NoodleBomb",
      "shrimp",
      "snap peas",
      "cabbage",
      "rice noodles"
    ],
    "steps": [
      "Cook vegetables or protein first over high heat.",
      "Add noodles or rice and toss until hot.",
      "Turn off the heat, add Citrus Shoyu, and toss hard for 20 seconds.",
      "Serve immediately with scallions or sesame."
    ],
    "tags": [
      "Citrus Shoyu",
      "Stir Fry",
      "Bright",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Citrus Shoyu Shrimp Stir Fry | NoodleBomb Stir Fry",
    "metaDescription": "Citrus Shoyu Shrimp Stir Fry made with NoodleBomb Citrus Shoyu. Fast stir fry idea with bold flavor and simple steps."
  },
  {
    "id": "citrus-shoyu-spring-roll-dip",
    "title": "Citrus Shoyu Spring Roll Dip",
    "slug": "citrus-shoyu-spring-roll-dip",
    "flavorId": "citrus-shoyu",
    "flavorName": "Citrus Shoyu",
    "flavorUrl": "/product/citrus-shoyu",
    "category": "dipping-sauce",
    "categoryLabel": "Dipping Sauces",
    "time": "3 min",
    "serves": "4",
    "difficulty": "Fast",
    "hook": "Make the dip people remember. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish.",
    "description": "Citrus Shoyu Spring Roll Dip turns dumplings, spring rolls, fries, or vegetables into a high-crave NoodleBomb use case with the bright bottle.",
    "ingredients": [
      "1/4 cup NoodleBomb",
      "rice vinegar",
      "ginger",
      "scallions"
    ],
    "steps": [
      "Whisk Citrus Shoyu with vinegar or sesame oil.",
      "Taste and adjust with lime, scallion, or chili crisp.",
      "Serve in a small bowl next to hot dumplings, rolls, fries, or grilled meat.",
      "Keep extra nearby because the first bowl goes fast."
    ],
    "tags": [
      "Citrus Shoyu",
      "Dipping Sauces",
      "Bright",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Citrus Shoyu Spring Roll Dip | NoodleBomb Dipping Sauces",
    "metaDescription": "Citrus Shoyu Spring Roll Dip made with NoodleBomb Citrus Shoyu. Fast dipping sauces idea with bold flavor and simple steps."
  },
  {
    "id": "shoyu-reserve-mushroom-ramen",
    "title": "Shoyu Reserve Mushroom Ramen",
    "slug": "shoyu-reserve-mushroom-ramen",
    "flavorId": "shoyu-reserve",
    "flavorName": "Shoyu Reserve",
    "flavorUrl": "/product/shoyu-reserve",
    "category": "ramen",
    "categoryLabel": "Ramen",
    "time": "10 min",
    "serves": "1",
    "difficulty": "Fast",
    "hook": "Turn a plain pack into a real bowl. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish.",
    "description": "Shoyu Reserve Mushroom Ramen turns ramen noodles into a high-crave NoodleBomb use case with the finishing and marinade bottle.",
    "ingredients": [
      "1 serving ramen noodles",
      "3-4 tbsp NoodleBomb",
      "mushrooms",
      "soft egg",
      "nori",
      "scallions"
    ],
    "steps": [
      "Cook noodles until springy, then drain or move into a hot bowl with a little broth.",
      "Add Shoyu Reserve and toss until the noodles are glossy.",
      "Add toppings while everything is still hot.",
      "Finish with Shoyu Reserve so the slow-brewed shoyu depth, mellow salt, and savory finish comes through."
    ],
    "tags": [
      "Shoyu Reserve",
      "Ramen",
      "Reserve",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Shoyu Reserve Mushroom Ramen | NoodleBomb Ramen",
    "metaDescription": "Shoyu Reserve Mushroom Ramen made with NoodleBomb Shoyu Reserve. Fast ramen idea with bold flavor and simple steps."
  },
  {
    "id": "shoyu-reserve-mushroom-rice-bowl",
    "title": "Shoyu Reserve Mushroom Rice Bowl",
    "slug": "shoyu-reserve-mushroom-rice-bowl",
    "flavorId": "shoyu-reserve",
    "flavorName": "Shoyu Reserve",
    "flavorUrl": "/product/shoyu-reserve",
    "category": "rice-bowl",
    "categoryLabel": "Rice Bowls",
    "time": "18 min",
    "serves": "2",
    "difficulty": "Fast",
    "hook": "Build a bowl that tastes planned. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish.",
    "description": "Shoyu Reserve Mushroom Rice Bowl turns warm rice into a high-crave NoodleBomb use case with the finishing and marinade bottle.",
    "ingredients": [
      "2 cups warm rice",
      "3-4 tbsp NoodleBomb",
      "roasted mushrooms",
      "jammy egg",
      "sesame greens"
    ],
    "steps": [
      "Start with hot rice and one crisp or seared protein.",
      "Add one fresh crunch topping and one rich topping.",
      "Spoon Shoyu Reserve over the center and fold lightly before eating.",
      "Add extra sauce at the table if the bowl needs more punch."
    ],
    "tags": [
      "Shoyu Reserve",
      "Rice Bowls",
      "Reserve",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Shoyu Reserve Mushroom Rice Bowl | NoodleBomb Rice Bowls",
    "metaDescription": "Shoyu Reserve Mushroom Rice Bowl made with NoodleBomb Shoyu Reserve. Fast rice bowls idea with bold flavor and simple steps."
  },
  {
    "id": "shoyu-reserve-black-pepper-wings",
    "title": "Shoyu Reserve Black Pepper Wings",
    "slug": "shoyu-reserve-black-pepper-wings",
    "flavorId": "shoyu-reserve",
    "flavorName": "Shoyu Reserve",
    "flavorUrl": "/product/shoyu-reserve",
    "category": "wings",
    "categoryLabel": "Wings",
    "time": "45 min",
    "serves": "4",
    "difficulty": "Easy",
    "hook": "Coat crispy wings without making them soggy. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish.",
    "description": "Shoyu Reserve Black Pepper Wings turns crispy wings into a high-crave NoodleBomb use case with the finishing and marinade bottle.",
    "ingredients": [
      "2 lb chicken wings",
      "3-4 tbsp NoodleBomb",
      "brown butter",
      "black pepper",
      "sesame"
    ],
    "steps": [
      "Bake or air-fry wings at 400 F until crisp.",
      "Warm Shoyu Reserve with butter or honey in a small pan.",
      "Toss hot wings with the sauce in a large bowl.",
      "Rest 2 minutes so the coating sets before serving."
    ],
    "tags": [
      "Shoyu Reserve",
      "Wings",
      "Reserve",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Shoyu Reserve Black Pepper Wings | NoodleBomb Wings",
    "metaDescription": "Shoyu Reserve Black Pepper Wings made with NoodleBomb Shoyu Reserve. Fast wings idea with bold flavor and simple steps."
  },
  {
    "id": "shoyu-reserve-pork-chop-marinade",
    "title": "Shoyu Reserve Pork Chop Marinade",
    "slug": "shoyu-reserve-pork-chop-marinade",
    "flavorId": "shoyu-reserve",
    "flavorName": "Shoyu Reserve",
    "flavorUrl": "/product/shoyu-reserve",
    "category": "marinade",
    "categoryLabel": "Marinades",
    "time": "25 min + marinate",
    "serves": "2",
    "difficulty": "Easy",
    "hook": "Use the sauce as the backbone of a fast marinade. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish.",
    "description": "Shoyu Reserve Pork Chop Marinade turns chicken, steak, tofu, or salmon into a high-crave NoodleBomb use case with the finishing and marinade bottle.",
    "ingredients": [
      "1 lb pork chops",
      "1/3 cup NoodleBomb",
      "garlic",
      "ginger",
      "brown sugar"
    ],
    "steps": [
      "Whisk Shoyu Reserve with oil and aromatics.",
      "Coat the protein and marinate 20 minutes to overnight depending on thickness.",
      "Cook hot and fast until browned.",
      "Rest, slice, then spoon a little fresh sauce over the top."
    ],
    "tags": [
      "Shoyu Reserve",
      "Marinades",
      "Reserve",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Shoyu Reserve Pork Chop Marinade | NoodleBomb Marinades",
    "metaDescription": "Shoyu Reserve Pork Chop Marinade made with NoodleBomb Shoyu Reserve. Fast marinades idea with bold flavor and simple steps."
  },
  {
    "id": "shoyu-reserve-mushroom-stir-fry",
    "title": "Shoyu Reserve Mushroom Stir Fry",
    "slug": "shoyu-reserve-mushroom-stir-fry",
    "flavorId": "shoyu-reserve",
    "flavorName": "Shoyu Reserve",
    "flavorUrl": "/product/shoyu-reserve",
    "category": "stir-fry",
    "categoryLabel": "Stir Fry",
    "time": "15 min",
    "serves": "2",
    "difficulty": "Fast",
    "hook": "Finish hot food with layered flavor. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish.",
    "description": "Shoyu Reserve Mushroom Stir Fry turns vegetables, noodles, or rice into a high-crave NoodleBomb use case with the finishing and marinade bottle.",
    "ingredients": [
      "2 cups vegetables, noodles, or rice",
      "3-4 tbsp NoodleBomb",
      "mushrooms",
      "onion",
      "greens",
      "noodles"
    ],
    "steps": [
      "Cook vegetables or protein first over high heat.",
      "Add noodles or rice and toss until hot.",
      "Turn off the heat, add Shoyu Reserve, and toss hard for 20 seconds.",
      "Serve immediately with scallions or sesame."
    ],
    "tags": [
      "Shoyu Reserve",
      "Stir Fry",
      "Reserve",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Shoyu Reserve Mushroom Stir Fry | NoodleBomb Stir Fry",
    "metaDescription": "Shoyu Reserve Mushroom Stir Fry made with NoodleBomb Shoyu Reserve. Fast stir fry idea with bold flavor and simple steps."
  },
  {
    "id": "shoyu-reserve-steak-dip",
    "title": "Shoyu Reserve Steak Dip",
    "slug": "shoyu-reserve-steak-dip",
    "flavorId": "shoyu-reserve",
    "flavorName": "Shoyu Reserve",
    "flavorUrl": "/product/shoyu-reserve",
    "category": "dipping-sauce",
    "categoryLabel": "Dipping Sauces",
    "time": "3 min",
    "serves": "4",
    "difficulty": "Fast",
    "hook": "Make the dip people remember. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish.",
    "description": "Shoyu Reserve Steak Dip turns dumplings, spring rolls, fries, or vegetables into a high-crave NoodleBomb use case with the finishing and marinade bottle.",
    "ingredients": [
      "1/4 cup NoodleBomb",
      "rice vinegar",
      "garlic",
      "sesame oil"
    ],
    "steps": [
      "Whisk Shoyu Reserve with vinegar or sesame oil.",
      "Taste and adjust with lime, scallion, or chili crisp.",
      "Serve in a small bowl next to hot dumplings, rolls, fries, or grilled meat.",
      "Keep extra nearby because the first bowl goes fast."
    ],
    "tags": [
      "Shoyu Reserve",
      "Dipping Sauces",
      "Reserve",
      "fast dinner",
      "NoodleBomb"
    ],
    "seoTitle": "Shoyu Reserve Steak Dip | NoodleBomb Dipping Sauces",
    "metaDescription": "Shoyu Reserve Steak Dip made with NoodleBomb Shoyu Reserve. Fast dipping sauces idea with bold flavor and simple steps."
  }
] satisfies RecipeContentItem[];
export const GENERATED_SOCIAL_POSTS = [
  {
    "id": "original-weeknight-ramen-bowl-reel",
    "channel": "instagram_reel",
    "recipeId": "original-weeknight-ramen-bowl",
    "flavorName": "Original",
    "hook": "Original Weeknight Ramen Bowl in 10 min.",
    "caption": "Original Weeknight Ramen Bowl: Turn a plain pack into a real bowl. Original brings deep soy, garlic, ginger, sesame, and balanced umami. Save this for the next time dinner feels boring. Shop Original at noodlebomb.co/product/original-ramen.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#Original"
    ]
  },
  {
    "id": "original-weeknight-ramen-bowl-pin",
    "channel": "pinterest",
    "recipeId": "original-weeknight-ramen-bowl",
    "flavorName": "Original",
    "hook": "Original Weeknight Ramen Bowl | NoodleBomb Ramen",
    "caption": "Original Weeknight Ramen Bowl made with NoodleBomb Original. Fast ramen idea with bold flavor and simple steps. Ingredients: 1 serving ramen noodles, 3-4 tbsp NoodleBomb, soft egg, scallions.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Ramen",
      "Original"
    ]
  },
  {
    "id": "original-crispy-chicken-rice-bowl-reel",
    "channel": "instagram_reel",
    "recipeId": "original-crispy-chicken-rice-bowl",
    "flavorName": "Original",
    "hook": "Original Crispy Chicken Rice Bowl in 18 min.",
    "caption": "Original Crispy Chicken Rice Bowl: Build a bowl that tastes planned. Original brings deep soy, garlic, ginger, sesame, and balanced umami. Save this for the next time dinner feels boring. Shop Original at noodlebomb.co/product/original-ramen.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#Original"
    ]
  },
  {
    "id": "original-crispy-chicken-rice-bowl-pin",
    "channel": "pinterest",
    "recipeId": "original-crispy-chicken-rice-bowl",
    "flavorName": "Original",
    "hook": "Original Crispy Chicken Rice Bowl | NoodleBomb Rice Bowls",
    "caption": "Original Crispy Chicken Rice Bowl made with NoodleBomb Original. Fast rice bowls idea with bold flavor and simple steps. Ingredients: 2 cups warm rice, 3-4 tbsp NoodleBomb, crispy chicken, cucumber.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Rice Bowls",
      "Original"
    ]
  },
  {
    "id": "original-sticky-sesame-wings-reel",
    "channel": "instagram_reel",
    "recipeId": "original-sticky-sesame-wings",
    "flavorName": "Original",
    "hook": "Original Sticky Sesame Wings in 45 min.",
    "caption": "Original Sticky Sesame Wings: Coat crispy wings without making them soggy. Original brings deep soy, garlic, ginger, sesame, and balanced umami. Save this for the next time dinner feels boring. Shop Original at noodlebomb.co/product/original-ramen.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#Original"
    ]
  },
  {
    "id": "original-sticky-sesame-wings-pin",
    "channel": "pinterest",
    "recipeId": "original-sticky-sesame-wings",
    "flavorName": "Original",
    "hook": "Original Sticky Sesame Wings | NoodleBomb Wings",
    "caption": "Original Sticky Sesame Wings made with NoodleBomb Original. Fast wings idea with bold flavor and simple steps. Ingredients: 2 lb chicken wings, 3-4 tbsp NoodleBomb, butter, honey.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Wings",
      "Original"
    ]
  },
  {
    "id": "original-garlic-chicken-marinade-reel",
    "channel": "instagram_reel",
    "recipeId": "original-garlic-chicken-marinade",
    "flavorName": "Original",
    "hook": "Original Garlic Chicken Marinade in 25 min + marinate.",
    "caption": "Original Garlic Chicken Marinade: Use the sauce as the backbone of a fast marinade. Original brings deep soy, garlic, ginger, sesame, and balanced umami. Save this for the next time dinner feels boring. Shop Original at noodlebomb.co/product/original-ramen.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#Original"
    ]
  },
  {
    "id": "original-garlic-chicken-marinade-pin",
    "channel": "pinterest",
    "recipeId": "original-garlic-chicken-marinade",
    "flavorName": "Original",
    "hook": "Original Garlic Chicken Marinade | NoodleBomb Marinades",
    "caption": "Original Garlic Chicken Marinade made with NoodleBomb Original. Fast marinades idea with bold flavor and simple steps. Ingredients: 1 lb chicken thighs, 1/3 cup NoodleBomb, ginger, garlic.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Marinades",
      "Original"
    ]
  },
  {
    "id": "original-broccoli-noodle-stir-fry-reel",
    "channel": "instagram_reel",
    "recipeId": "original-broccoli-noodle-stir-fry",
    "flavorName": "Original",
    "hook": "Original Broccoli Noodle Stir Fry in 15 min.",
    "caption": "Original Broccoli Noodle Stir Fry: Finish hot food with layered flavor. Original brings deep soy, garlic, ginger, sesame, and balanced umami. Save this for the next time dinner feels boring. Shop Original at noodlebomb.co/product/original-ramen.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#Original"
    ]
  },
  {
    "id": "original-broccoli-noodle-stir-fry-pin",
    "channel": "pinterest",
    "recipeId": "original-broccoli-noodle-stir-fry",
    "flavorName": "Original",
    "hook": "Original Broccoli Noodle Stir Fry | NoodleBomb Stir Fry",
    "caption": "Original Broccoli Noodle Stir Fry made with NoodleBomb Original. Fast stir fry idea with bold flavor and simple steps. Ingredients: 2 cups vegetables, noodles, or rice, 3-4 tbsp NoodleBomb, broccoli, mushrooms.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Stir Fry",
      "Original"
    ]
  },
  {
    "id": "original-dumpling-dip-reel",
    "channel": "instagram_reel",
    "recipeId": "original-dumpling-dip",
    "flavorName": "Original",
    "hook": "Original Dumpling Dip in 3 min.",
    "caption": "Original Dumpling Dip: Make the dip people remember. Original brings deep soy, garlic, ginger, sesame, and balanced umami. Save this for the next time dinner feels boring. Shop Original at noodlebomb.co/product/original-ramen.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#Original"
    ]
  },
  {
    "id": "original-dumpling-dip-pin",
    "channel": "pinterest",
    "recipeId": "original-dumpling-dip",
    "flavorName": "Original",
    "hook": "Original Dumpling Dip | NoodleBomb Dipping Sauces",
    "caption": "Original Dumpling Dip made with NoodleBomb Original. Fast dipping sauces idea with bold flavor and simple steps. Ingredients: 1/4 cup NoodleBomb, rice vinegar, sesame oil, scallions.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Dipping Sauces",
      "Original"
    ]
  },
  {
    "id": "spicy-tokyo-fire-ramen-reel",
    "channel": "instagram_reel",
    "recipeId": "spicy-tokyo-fire-ramen",
    "flavorName": "Spicy Tokyo",
    "hook": "Spicy Tokyo Fire Ramen in 10 min.",
    "caption": "Spicy Tokyo Fire Ramen: Turn a plain pack into a real bowl. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame. Save this for the next time dinner feels boring. Shop Spicy Tokyo at noodlebomb.co/product/spicy-tokyo.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#SpicyTokyo"
    ]
  },
  {
    "id": "spicy-tokyo-fire-ramen-pin",
    "channel": "pinterest",
    "recipeId": "spicy-tokyo-fire-ramen",
    "flavorName": "Spicy Tokyo",
    "hook": "Spicy Tokyo Fire Ramen | NoodleBomb Ramen",
    "caption": "Spicy Tokyo Fire Ramen made with NoodleBomb Spicy Tokyo. Fast ramen idea with bold flavor and simple steps. Ingredients: 1 serving ramen noodles, 3-4 tbsp NoodleBomb, ground pork, chili oil.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Ramen",
      "Spicy Tokyo"
    ]
  },
  {
    "id": "spicy-tokyo-steak-rice-bowl-reel",
    "channel": "instagram_reel",
    "recipeId": "spicy-tokyo-steak-rice-bowl",
    "flavorName": "Spicy Tokyo",
    "hook": "Spicy Tokyo Steak Rice Bowl in 18 min.",
    "caption": "Spicy Tokyo Steak Rice Bowl: Build a bowl that tastes planned. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame. Save this for the next time dinner feels boring. Shop Spicy Tokyo at noodlebomb.co/product/spicy-tokyo.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#SpicyTokyo"
    ]
  },
  {
    "id": "spicy-tokyo-steak-rice-bowl-pin",
    "channel": "pinterest",
    "recipeId": "spicy-tokyo-steak-rice-bowl",
    "flavorName": "Spicy Tokyo",
    "hook": "Spicy Tokyo Steak Rice Bowl | NoodleBomb Rice Bowls",
    "caption": "Spicy Tokyo Steak Rice Bowl made with NoodleBomb Spicy Tokyo. Fast rice bowls idea with bold flavor and simple steps. Ingredients: 2 cups warm rice, 3-4 tbsp NoodleBomb, steak, kimchi.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Rice Bowls",
      "Spicy Tokyo"
    ]
  },
  {
    "id": "spicy-tokyo-chili-wings-reel",
    "channel": "instagram_reel",
    "recipeId": "spicy-tokyo-chili-wings",
    "flavorName": "Spicy Tokyo",
    "hook": "Spicy Tokyo Chili Wings in 45 min.",
    "caption": "Spicy Tokyo Chili Wings: Coat crispy wings without making them soggy. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame. Save this for the next time dinner feels boring. Shop Spicy Tokyo at noodlebomb.co/product/spicy-tokyo.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#SpicyTokyo"
    ]
  },
  {
    "id": "spicy-tokyo-chili-wings-pin",
    "channel": "pinterest",
    "recipeId": "spicy-tokyo-chili-wings",
    "flavorName": "Spicy Tokyo",
    "hook": "Spicy Tokyo Chili Wings | NoodleBomb Wings",
    "caption": "Spicy Tokyo Chili Wings made with NoodleBomb Spicy Tokyo. Fast wings idea with bold flavor and simple steps. Ingredients: 2 lb chicken wings, 3-4 tbsp NoodleBomb, butter, lime.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Wings",
      "Spicy Tokyo"
    ]
  },
  {
    "id": "spicy-tokyo-steak-marinade-reel",
    "channel": "instagram_reel",
    "recipeId": "spicy-tokyo-steak-marinade",
    "flavorName": "Spicy Tokyo",
    "hook": "Spicy Tokyo Steak Marinade in 25 min + marinate.",
    "caption": "Spicy Tokyo Steak Marinade: Use the sauce as the backbone of a fast marinade. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame. Save this for the next time dinner feels boring. Shop Spicy Tokyo at noodlebomb.co/product/spicy-tokyo.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#SpicyTokyo"
    ]
  },
  {
    "id": "spicy-tokyo-steak-marinade-pin",
    "channel": "pinterest",
    "recipeId": "spicy-tokyo-steak-marinade",
    "flavorName": "Spicy Tokyo",
    "hook": "Spicy Tokyo Steak Marinade | NoodleBomb Marinades",
    "caption": "Spicy Tokyo Steak Marinade made with NoodleBomb Spicy Tokyo. Fast marinades idea with bold flavor and simple steps. Ingredients: 1 lb flank steak, 1/3 cup NoodleBomb, garlic, sesame oil.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Marinades",
      "Spicy Tokyo"
    ]
  },
  {
    "id": "spicy-tokyo-udon-stir-fry-reel",
    "channel": "instagram_reel",
    "recipeId": "spicy-tokyo-udon-stir-fry",
    "flavorName": "Spicy Tokyo",
    "hook": "Spicy Tokyo Udon Stir Fry in 15 min.",
    "caption": "Spicy Tokyo Udon Stir Fry: Finish hot food with layered flavor. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame. Save this for the next time dinner feels boring. Shop Spicy Tokyo at noodlebomb.co/product/spicy-tokyo.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#SpicyTokyo"
    ]
  },
  {
    "id": "spicy-tokyo-udon-stir-fry-pin",
    "channel": "pinterest",
    "recipeId": "spicy-tokyo-udon-stir-fry",
    "flavorName": "Spicy Tokyo",
    "hook": "Spicy Tokyo Udon Stir Fry | NoodleBomb Stir Fry",
    "caption": "Spicy Tokyo Udon Stir Fry made with NoodleBomb Spicy Tokyo. Fast stir fry idea with bold flavor and simple steps. Ingredients: 2 cups vegetables, noodles, or rice, 3-4 tbsp NoodleBomb, udon, bok choy.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Stir Fry",
      "Spicy Tokyo"
    ]
  },
  {
    "id": "spicy-tokyo-gyoza-dip-reel",
    "channel": "instagram_reel",
    "recipeId": "spicy-tokyo-gyoza-dip",
    "flavorName": "Spicy Tokyo",
    "hook": "Spicy Tokyo Gyoza Dip in 3 min.",
    "caption": "Spicy Tokyo Gyoza Dip: Make the dip people remember. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame. Save this for the next time dinner feels boring. Shop Spicy Tokyo at noodlebomb.co/product/spicy-tokyo.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#SpicyTokyo"
    ]
  },
  {
    "id": "spicy-tokyo-gyoza-dip-pin",
    "channel": "pinterest",
    "recipeId": "spicy-tokyo-gyoza-dip",
    "flavorName": "Spicy Tokyo",
    "hook": "Spicy Tokyo Gyoza Dip | NoodleBomb Dipping Sauces",
    "caption": "Spicy Tokyo Gyoza Dip made with NoodleBomb Spicy Tokyo. Fast dipping sauces idea with bold flavor and simple steps. Ingredients: 1/4 cup NoodleBomb, rice vinegar, chili crisp, sesame oil.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Dipping Sauces",
      "Spicy Tokyo"
    ]
  },
  {
    "id": "citrus-shoyu-cold-noodle-bowl-reel",
    "channel": "instagram_reel",
    "recipeId": "citrus-shoyu-cold-noodle-bowl",
    "flavorName": "Citrus Shoyu",
    "hook": "Citrus Shoyu Cold Noodle Bowl in 10 min.",
    "caption": "Citrus Shoyu Cold Noodle Bowl: Turn a plain pack into a real bowl. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish. Save this for the next time dinner feels boring. Shop Citrus Shoyu at noodlebomb.co/product/citrus-shoyu.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#CitrusShoyu"
    ]
  },
  {
    "id": "citrus-shoyu-cold-noodle-bowl-pin",
    "channel": "pinterest",
    "recipeId": "citrus-shoyu-cold-noodle-bowl",
    "flavorName": "Citrus Shoyu",
    "hook": "Citrus Shoyu Cold Noodle Bowl | NoodleBomb Ramen",
    "caption": "Citrus Shoyu Cold Noodle Bowl made with NoodleBomb Citrus Shoyu. Fast ramen idea with bold flavor and simple steps. Ingredients: 1 serving ramen noodles, 3-4 tbsp NoodleBomb, cold noodles, cucumber.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Ramen",
      "Citrus Shoyu"
    ]
  },
  {
    "id": "citrus-shoyu-salmon-rice-bowl-reel",
    "channel": "instagram_reel",
    "recipeId": "citrus-shoyu-salmon-rice-bowl",
    "flavorName": "Citrus Shoyu",
    "hook": "Citrus Shoyu Salmon Rice Bowl in 18 min.",
    "caption": "Citrus Shoyu Salmon Rice Bowl: Build a bowl that tastes planned. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish. Save this for the next time dinner feels boring. Shop Citrus Shoyu at noodlebomb.co/product/citrus-shoyu.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#CitrusShoyu"
    ]
  },
  {
    "id": "citrus-shoyu-salmon-rice-bowl-pin",
    "channel": "pinterest",
    "recipeId": "citrus-shoyu-salmon-rice-bowl",
    "flavorName": "Citrus Shoyu",
    "hook": "Citrus Shoyu Salmon Rice Bowl | NoodleBomb Rice Bowls",
    "caption": "Citrus Shoyu Salmon Rice Bowl made with NoodleBomb Citrus Shoyu. Fast rice bowls idea with bold flavor and simple steps. Ingredients: 2 cups warm rice, 3-4 tbsp NoodleBomb, salmon, avocado.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Rice Bowls",
      "Citrus Shoyu"
    ]
  },
  {
    "id": "citrus-shoyu-honey-wings-reel",
    "channel": "instagram_reel",
    "recipeId": "citrus-shoyu-honey-wings",
    "flavorName": "Citrus Shoyu",
    "hook": "Citrus Shoyu Honey Wings in 45 min.",
    "caption": "Citrus Shoyu Honey Wings: Coat crispy wings without making them soggy. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish. Save this for the next time dinner feels boring. Shop Citrus Shoyu at noodlebomb.co/product/citrus-shoyu.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#CitrusShoyu"
    ]
  },
  {
    "id": "citrus-shoyu-honey-wings-pin",
    "channel": "pinterest",
    "recipeId": "citrus-shoyu-honey-wings",
    "flavorName": "Citrus Shoyu",
    "hook": "Citrus Shoyu Honey Wings | NoodleBomb Wings",
    "caption": "Citrus Shoyu Honey Wings made with NoodleBomb Citrus Shoyu. Fast wings idea with bold flavor and simple steps. Ingredients: 2 lb chicken wings, 3-4 tbsp NoodleBomb, lime, honey.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Wings",
      "Citrus Shoyu"
    ]
  },
  {
    "id": "citrus-shoyu-salmon-marinade-reel",
    "channel": "instagram_reel",
    "recipeId": "citrus-shoyu-salmon-marinade",
    "flavorName": "Citrus Shoyu",
    "hook": "Citrus Shoyu Salmon Marinade in 25 min + marinate.",
    "caption": "Citrus Shoyu Salmon Marinade: Use the sauce as the backbone of a fast marinade. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish. Save this for the next time dinner feels boring. Shop Citrus Shoyu at noodlebomb.co/product/citrus-shoyu.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#CitrusShoyu"
    ]
  },
  {
    "id": "citrus-shoyu-salmon-marinade-pin",
    "channel": "pinterest",
    "recipeId": "citrus-shoyu-salmon-marinade",
    "flavorName": "Citrus Shoyu",
    "hook": "Citrus Shoyu Salmon Marinade | NoodleBomb Marinades",
    "caption": "Citrus Shoyu Salmon Marinade made with NoodleBomb Citrus Shoyu. Fast marinades idea with bold flavor and simple steps. Ingredients: 1 lb salmon, 1/3 cup NoodleBomb, ginger, orange.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Marinades",
      "Citrus Shoyu"
    ]
  },
  {
    "id": "citrus-shoyu-shrimp-stir-fry-reel",
    "channel": "instagram_reel",
    "recipeId": "citrus-shoyu-shrimp-stir-fry",
    "flavorName": "Citrus Shoyu",
    "hook": "Citrus Shoyu Shrimp Stir Fry in 15 min.",
    "caption": "Citrus Shoyu Shrimp Stir Fry: Finish hot food with layered flavor. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish. Save this for the next time dinner feels boring. Shop Citrus Shoyu at noodlebomb.co/product/citrus-shoyu.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#CitrusShoyu"
    ]
  },
  {
    "id": "citrus-shoyu-shrimp-stir-fry-pin",
    "channel": "pinterest",
    "recipeId": "citrus-shoyu-shrimp-stir-fry",
    "flavorName": "Citrus Shoyu",
    "hook": "Citrus Shoyu Shrimp Stir Fry | NoodleBomb Stir Fry",
    "caption": "Citrus Shoyu Shrimp Stir Fry made with NoodleBomb Citrus Shoyu. Fast stir fry idea with bold flavor and simple steps. Ingredients: 2 cups vegetables, noodles, or rice, 3-4 tbsp NoodleBomb, shrimp, snap peas.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Stir Fry",
      "Citrus Shoyu"
    ]
  },
  {
    "id": "citrus-shoyu-spring-roll-dip-reel",
    "channel": "instagram_reel",
    "recipeId": "citrus-shoyu-spring-roll-dip",
    "flavorName": "Citrus Shoyu",
    "hook": "Citrus Shoyu Spring Roll Dip in 3 min.",
    "caption": "Citrus Shoyu Spring Roll Dip: Make the dip people remember. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish. Save this for the next time dinner feels boring. Shop Citrus Shoyu at noodlebomb.co/product/citrus-shoyu.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#CitrusShoyu"
    ]
  },
  {
    "id": "citrus-shoyu-spring-roll-dip-pin",
    "channel": "pinterest",
    "recipeId": "citrus-shoyu-spring-roll-dip",
    "flavorName": "Citrus Shoyu",
    "hook": "Citrus Shoyu Spring Roll Dip | NoodleBomb Dipping Sauces",
    "caption": "Citrus Shoyu Spring Roll Dip made with NoodleBomb Citrus Shoyu. Fast dipping sauces idea with bold flavor and simple steps. Ingredients: 1/4 cup NoodleBomb, rice vinegar, ginger, scallions.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Dipping Sauces",
      "Citrus Shoyu"
    ]
  },
  {
    "id": "shoyu-reserve-mushroom-ramen-reel",
    "channel": "instagram_reel",
    "recipeId": "shoyu-reserve-mushroom-ramen",
    "flavorName": "Shoyu Reserve",
    "hook": "Shoyu Reserve Mushroom Ramen in 10 min.",
    "caption": "Shoyu Reserve Mushroom Ramen: Turn a plain pack into a real bowl. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish. Save this for the next time dinner feels boring. Shop Shoyu Reserve at noodlebomb.co/product/shoyu-reserve.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#ShoyuReserve"
    ]
  },
  {
    "id": "shoyu-reserve-mushroom-ramen-pin",
    "channel": "pinterest",
    "recipeId": "shoyu-reserve-mushroom-ramen",
    "flavorName": "Shoyu Reserve",
    "hook": "Shoyu Reserve Mushroom Ramen | NoodleBomb Ramen",
    "caption": "Shoyu Reserve Mushroom Ramen made with NoodleBomb Shoyu Reserve. Fast ramen idea with bold flavor and simple steps. Ingredients: 1 serving ramen noodles, 3-4 tbsp NoodleBomb, mushrooms, soft egg.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Ramen",
      "Shoyu Reserve"
    ]
  },
  {
    "id": "shoyu-reserve-mushroom-rice-bowl-reel",
    "channel": "instagram_reel",
    "recipeId": "shoyu-reserve-mushroom-rice-bowl",
    "flavorName": "Shoyu Reserve",
    "hook": "Shoyu Reserve Mushroom Rice Bowl in 18 min.",
    "caption": "Shoyu Reserve Mushroom Rice Bowl: Build a bowl that tastes planned. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish. Save this for the next time dinner feels boring. Shop Shoyu Reserve at noodlebomb.co/product/shoyu-reserve.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#ShoyuReserve"
    ]
  },
  {
    "id": "shoyu-reserve-mushroom-rice-bowl-pin",
    "channel": "pinterest",
    "recipeId": "shoyu-reserve-mushroom-rice-bowl",
    "flavorName": "Shoyu Reserve",
    "hook": "Shoyu Reserve Mushroom Rice Bowl | NoodleBomb Rice Bowls",
    "caption": "Shoyu Reserve Mushroom Rice Bowl made with NoodleBomb Shoyu Reserve. Fast rice bowls idea with bold flavor and simple steps. Ingredients: 2 cups warm rice, 3-4 tbsp NoodleBomb, roasted mushrooms, jammy egg.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Rice Bowls",
      "Shoyu Reserve"
    ]
  },
  {
    "id": "shoyu-reserve-black-pepper-wings-reel",
    "channel": "instagram_reel",
    "recipeId": "shoyu-reserve-black-pepper-wings",
    "flavorName": "Shoyu Reserve",
    "hook": "Shoyu Reserve Black Pepper Wings in 45 min.",
    "caption": "Shoyu Reserve Black Pepper Wings: Coat crispy wings without making them soggy. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish. Save this for the next time dinner feels boring. Shop Shoyu Reserve at noodlebomb.co/product/shoyu-reserve.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#ShoyuReserve"
    ]
  },
  {
    "id": "shoyu-reserve-black-pepper-wings-pin",
    "channel": "pinterest",
    "recipeId": "shoyu-reserve-black-pepper-wings",
    "flavorName": "Shoyu Reserve",
    "hook": "Shoyu Reserve Black Pepper Wings | NoodleBomb Wings",
    "caption": "Shoyu Reserve Black Pepper Wings made with NoodleBomb Shoyu Reserve. Fast wings idea with bold flavor and simple steps. Ingredients: 2 lb chicken wings, 3-4 tbsp NoodleBomb, brown butter, black pepper.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Wings",
      "Shoyu Reserve"
    ]
  },
  {
    "id": "shoyu-reserve-pork-chop-marinade-reel",
    "channel": "instagram_reel",
    "recipeId": "shoyu-reserve-pork-chop-marinade",
    "flavorName": "Shoyu Reserve",
    "hook": "Shoyu Reserve Pork Chop Marinade in 25 min + marinate.",
    "caption": "Shoyu Reserve Pork Chop Marinade: Use the sauce as the backbone of a fast marinade. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish. Save this for the next time dinner feels boring. Shop Shoyu Reserve at noodlebomb.co/product/shoyu-reserve.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#ShoyuReserve"
    ]
  },
  {
    "id": "shoyu-reserve-pork-chop-marinade-pin",
    "channel": "pinterest",
    "recipeId": "shoyu-reserve-pork-chop-marinade",
    "flavorName": "Shoyu Reserve",
    "hook": "Shoyu Reserve Pork Chop Marinade | NoodleBomb Marinades",
    "caption": "Shoyu Reserve Pork Chop Marinade made with NoodleBomb Shoyu Reserve. Fast marinades idea with bold flavor and simple steps. Ingredients: 1 lb pork chops, 1/3 cup NoodleBomb, garlic, ginger.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Marinades",
      "Shoyu Reserve"
    ]
  },
  {
    "id": "shoyu-reserve-mushroom-stir-fry-reel",
    "channel": "instagram_reel",
    "recipeId": "shoyu-reserve-mushroom-stir-fry",
    "flavorName": "Shoyu Reserve",
    "hook": "Shoyu Reserve Mushroom Stir Fry in 15 min.",
    "caption": "Shoyu Reserve Mushroom Stir Fry: Finish hot food with layered flavor. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish. Save this for the next time dinner feels boring. Shop Shoyu Reserve at noodlebomb.co/product/shoyu-reserve.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#ShoyuReserve"
    ]
  },
  {
    "id": "shoyu-reserve-mushroom-stir-fry-pin",
    "channel": "pinterest",
    "recipeId": "shoyu-reserve-mushroom-stir-fry",
    "flavorName": "Shoyu Reserve",
    "hook": "Shoyu Reserve Mushroom Stir Fry | NoodleBomb Stir Fry",
    "caption": "Shoyu Reserve Mushroom Stir Fry made with NoodleBomb Shoyu Reserve. Fast stir fry idea with bold flavor and simple steps. Ingredients: 2 cups vegetables, noodles, or rice, 3-4 tbsp NoodleBomb, mushrooms, onion.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Stir Fry",
      "Shoyu Reserve"
    ]
  },
  {
    "id": "shoyu-reserve-steak-dip-reel",
    "channel": "instagram_reel",
    "recipeId": "shoyu-reserve-steak-dip",
    "flavorName": "Shoyu Reserve",
    "hook": "Shoyu Reserve Steak Dip in 3 min.",
    "caption": "Shoyu Reserve Steak Dip: Make the dip people remember. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish. Save this for the next time dinner feels boring. Shop Shoyu Reserve at noodlebomb.co/product/shoyu-reserve.",
    "shotList": [
      "Bottle next to finished dish",
      "Close-up sauce hitting hot food",
      "Final bite pull or crunch shot"
    ],
    "hashtags": [
      "#NoodleBomb",
      "#RamenSauce",
      "#EasyDinner",
      "#ShoyuReserve"
    ]
  },
  {
    "id": "shoyu-reserve-steak-dip-pin",
    "channel": "pinterest",
    "recipeId": "shoyu-reserve-steak-dip",
    "flavorName": "Shoyu Reserve",
    "hook": "Shoyu Reserve Steak Dip | NoodleBomb Dipping Sauces",
    "caption": "Shoyu Reserve Steak Dip made with NoodleBomb Shoyu Reserve. Fast dipping sauces idea with bold flavor and simple steps. Ingredients: 1/4 cup NoodleBomb, rice vinegar, garlic, sesame oil.",
    "shotList": [
      "Overhead finished plate",
      "Ingredient layout",
      "Bottle in frame"
    ],
    "hashtags": [
      "NoodleBomb",
      "Dipping Sauces",
      "Shoyu Reserve"
    ]
  }
] satisfies RecipeSocialPost[];
export const GENERATED_BLOG_POSTS = [
  {
    "slug": "best-noodlebomb-ramen",
    "title": "Best NoodleBomb Ramen Ideas",
    "description": "4 fast ramen ideas organized by flavor.",
    "recipes": [
      "original-weeknight-ramen-bowl",
      "spicy-tokyo-fire-ramen",
      "citrus-shoyu-cold-noodle-bowl",
      "shoyu-reserve-mushroom-ramen"
    ],
    "body": "# Best NoodleBomb Ramen Ideas\n\nThese ramen ideas show how each NoodleBomb flavor changes the same use case.\n\n## Original Weeknight Ramen Bowl\nOriginal Weeknight Ramen Bowl turns ramen noodles into a high-crave NoodleBomb use case with the all-purpose bottle.\nShop: /product/original-ramen\n\n## Spicy Tokyo Fire Ramen\nSpicy Tokyo Fire Ramen turns ramen noodles into a high-crave NoodleBomb use case with the heat-forward bottle.\nShop: /product/spicy-tokyo\n\n## Citrus Shoyu Cold Noodle Bowl\nCitrus Shoyu Cold Noodle Bowl turns ramen noodles into a high-crave NoodleBomb use case with the bright bottle.\nShop: /product/citrus-shoyu\n\n## Shoyu Reserve Mushroom Ramen\nShoyu Reserve Mushroom Ramen turns ramen noodles into a high-crave NoodleBomb use case with the finishing and marinade bottle.\nShop: /product/shoyu-reserve\n"
  },
  {
    "slug": "best-noodlebomb-rice-bowls",
    "title": "Best NoodleBomb Rice Bowls Ideas",
    "description": "4 fast rice bowls ideas organized by flavor.",
    "recipes": [
      "original-crispy-chicken-rice-bowl",
      "spicy-tokyo-steak-rice-bowl",
      "citrus-shoyu-salmon-rice-bowl",
      "shoyu-reserve-mushroom-rice-bowl"
    ],
    "body": "# Best NoodleBomb Rice Bowls Ideas\n\nThese rice bowls ideas show how each NoodleBomb flavor changes the same use case.\n\n## Original Crispy Chicken Rice Bowl\nOriginal Crispy Chicken Rice Bowl turns warm rice into a high-crave NoodleBomb use case with the all-purpose bottle.\nShop: /product/original-ramen\n\n## Spicy Tokyo Steak Rice Bowl\nSpicy Tokyo Steak Rice Bowl turns warm rice into a high-crave NoodleBomb use case with the heat-forward bottle.\nShop: /product/spicy-tokyo\n\n## Citrus Shoyu Salmon Rice Bowl\nCitrus Shoyu Salmon Rice Bowl turns warm rice into a high-crave NoodleBomb use case with the bright bottle.\nShop: /product/citrus-shoyu\n\n## Shoyu Reserve Mushroom Rice Bowl\nShoyu Reserve Mushroom Rice Bowl turns warm rice into a high-crave NoodleBomb use case with the finishing and marinade bottle.\nShop: /product/shoyu-reserve\n"
  },
  {
    "slug": "best-noodlebomb-wings",
    "title": "Best NoodleBomb Wings Ideas",
    "description": "4 fast wings ideas organized by flavor.",
    "recipes": [
      "original-sticky-sesame-wings",
      "spicy-tokyo-chili-wings",
      "citrus-shoyu-honey-wings",
      "shoyu-reserve-black-pepper-wings"
    ],
    "body": "# Best NoodleBomb Wings Ideas\n\nThese wings ideas show how each NoodleBomb flavor changes the same use case.\n\n## Original Sticky Sesame Wings\nOriginal Sticky Sesame Wings turns crispy wings into a high-crave NoodleBomb use case with the all-purpose bottle.\nShop: /product/original-ramen\n\n## Spicy Tokyo Chili Wings\nSpicy Tokyo Chili Wings turns crispy wings into a high-crave NoodleBomb use case with the heat-forward bottle.\nShop: /product/spicy-tokyo\n\n## Citrus Shoyu Honey Wings\nCitrus Shoyu Honey Wings turns crispy wings into a high-crave NoodleBomb use case with the bright bottle.\nShop: /product/citrus-shoyu\n\n## Shoyu Reserve Black Pepper Wings\nShoyu Reserve Black Pepper Wings turns crispy wings into a high-crave NoodleBomb use case with the finishing and marinade bottle.\nShop: /product/shoyu-reserve\n"
  },
  {
    "slug": "best-noodlebomb-marinades",
    "title": "Best NoodleBomb Marinades Ideas",
    "description": "4 fast marinades ideas organized by flavor.",
    "recipes": [
      "original-garlic-chicken-marinade",
      "spicy-tokyo-steak-marinade",
      "citrus-shoyu-salmon-marinade",
      "shoyu-reserve-pork-chop-marinade"
    ],
    "body": "# Best NoodleBomb Marinades Ideas\n\nThese marinades ideas show how each NoodleBomb flavor changes the same use case.\n\n## Original Garlic Chicken Marinade\nOriginal Garlic Chicken Marinade turns chicken, steak, tofu, or salmon into a high-crave NoodleBomb use case with the all-purpose bottle.\nShop: /product/original-ramen\n\n## Spicy Tokyo Steak Marinade\nSpicy Tokyo Steak Marinade turns chicken, steak, tofu, or salmon into a high-crave NoodleBomb use case with the heat-forward bottle.\nShop: /product/spicy-tokyo\n\n## Citrus Shoyu Salmon Marinade\nCitrus Shoyu Salmon Marinade turns chicken, steak, tofu, or salmon into a high-crave NoodleBomb use case with the bright bottle.\nShop: /product/citrus-shoyu\n\n## Shoyu Reserve Pork Chop Marinade\nShoyu Reserve Pork Chop Marinade turns chicken, steak, tofu, or salmon into a high-crave NoodleBomb use case with the finishing and marinade bottle.\nShop: /product/shoyu-reserve\n"
  },
  {
    "slug": "best-noodlebomb-stir-fry",
    "title": "Best NoodleBomb Stir Fry Ideas",
    "description": "4 fast stir fry ideas organized by flavor.",
    "recipes": [
      "original-broccoli-noodle-stir-fry",
      "spicy-tokyo-udon-stir-fry",
      "citrus-shoyu-shrimp-stir-fry",
      "shoyu-reserve-mushroom-stir-fry"
    ],
    "body": "# Best NoodleBomb Stir Fry Ideas\n\nThese stir fry ideas show how each NoodleBomb flavor changes the same use case.\n\n## Original Broccoli Noodle Stir Fry\nOriginal Broccoli Noodle Stir Fry turns vegetables, noodles, or rice into a high-crave NoodleBomb use case with the all-purpose bottle.\nShop: /product/original-ramen\n\n## Spicy Tokyo Udon Stir Fry\nSpicy Tokyo Udon Stir Fry turns vegetables, noodles, or rice into a high-crave NoodleBomb use case with the heat-forward bottle.\nShop: /product/spicy-tokyo\n\n## Citrus Shoyu Shrimp Stir Fry\nCitrus Shoyu Shrimp Stir Fry turns vegetables, noodles, or rice into a high-crave NoodleBomb use case with the bright bottle.\nShop: /product/citrus-shoyu\n\n## Shoyu Reserve Mushroom Stir Fry\nShoyu Reserve Mushroom Stir Fry turns vegetables, noodles, or rice into a high-crave NoodleBomb use case with the finishing and marinade bottle.\nShop: /product/shoyu-reserve\n"
  },
  {
    "slug": "best-noodlebomb-dipping-sauces",
    "title": "Best NoodleBomb Dipping Sauces Ideas",
    "description": "4 fast dipping sauces ideas organized by flavor.",
    "recipes": [
      "original-dumpling-dip",
      "spicy-tokyo-gyoza-dip",
      "citrus-shoyu-spring-roll-dip",
      "shoyu-reserve-steak-dip"
    ],
    "body": "# Best NoodleBomb Dipping Sauces Ideas\n\nThese dipping sauces ideas show how each NoodleBomb flavor changes the same use case.\n\n## Original Dumpling Dip\nOriginal Dumpling Dip turns dumplings, spring rolls, fries, or vegetables into a high-crave NoodleBomb use case with the all-purpose bottle.\nShop: /product/original-ramen\n\n## Spicy Tokyo Gyoza Dip\nSpicy Tokyo Gyoza Dip turns dumplings, spring rolls, fries, or vegetables into a high-crave NoodleBomb use case with the heat-forward bottle.\nShop: /product/spicy-tokyo\n\n## Citrus Shoyu Spring Roll Dip\nCitrus Shoyu Spring Roll Dip turns dumplings, spring rolls, fries, or vegetables into a high-crave NoodleBomb use case with the bright bottle.\nShop: /product/citrus-shoyu\n\n## Shoyu Reserve Steak Dip\nShoyu Reserve Steak Dip turns dumplings, spring rolls, fries, or vegetables into a high-crave NoodleBomb use case with the finishing and marinade bottle.\nShop: /product/shoyu-reserve\n"
  },
  {
    "slug": "how-to-use-noodlebomb-original",
    "title": "How to Use NoodleBomb Original",
    "description": "Original recipe ideas for noodles, rice bowls, wings, marinades, stir fry, and dips.",
    "recipes": [
      "original-weeknight-ramen-bowl",
      "original-crispy-chicken-rice-bowl",
      "original-sticky-sesame-wings",
      "original-garlic-chicken-marinade",
      "original-broccoli-noodle-stir-fry",
      "original-dumpling-dip"
    ],
    "body": "# How to Use NoodleBomb Original\n\nOriginal is the all-purpose bottle: deep soy, garlic, ginger, sesame, and balanced umami.\n\n## Original Weeknight Ramen Bowl\nTurn a plain pack into a real bowl. Original brings deep soy, garlic, ginger, sesame, and balanced umami.\nBest for: Ramen.\n\n## Original Crispy Chicken Rice Bowl\nBuild a bowl that tastes planned. Original brings deep soy, garlic, ginger, sesame, and balanced umami.\nBest for: Rice Bowls.\n\n## Original Sticky Sesame Wings\nCoat crispy wings without making them soggy. Original brings deep soy, garlic, ginger, sesame, and balanced umami.\nBest for: Wings.\n\n## Original Garlic Chicken Marinade\nUse the sauce as the backbone of a fast marinade. Original brings deep soy, garlic, ginger, sesame, and balanced umami.\nBest for: Marinades.\n\n## Original Broccoli Noodle Stir Fry\nFinish hot food with layered flavor. Original brings deep soy, garlic, ginger, sesame, and balanced umami.\nBest for: Stir Fry.\n\n## Original Dumpling Dip\nMake the dip people remember. Original brings deep soy, garlic, ginger, sesame, and balanced umami.\nBest for: Dipping Sauces.\n"
  },
  {
    "slug": "how-to-use-noodlebomb-spicy-tokyo",
    "title": "How to Use NoodleBomb Spicy Tokyo",
    "description": "Spicy Tokyo recipe ideas for noodles, rice bowls, wings, marinades, stir fry, and dips.",
    "recipes": [
      "spicy-tokyo-fire-ramen",
      "spicy-tokyo-steak-rice-bowl",
      "spicy-tokyo-chili-wings",
      "spicy-tokyo-steak-marinade",
      "spicy-tokyo-udon-stir-fry",
      "spicy-tokyo-gyoza-dip"
    ],
    "body": "# How to Use NoodleBomb Spicy Tokyo\n\nSpicy Tokyo is the heat-forward bottle: roasted chili heat, dark soy depth, garlic, and sesame.\n\n## Spicy Tokyo Fire Ramen\nTurn a plain pack into a real bowl. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame.\nBest for: Ramen.\n\n## Spicy Tokyo Steak Rice Bowl\nBuild a bowl that tastes planned. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame.\nBest for: Rice Bowls.\n\n## Spicy Tokyo Chili Wings\nCoat crispy wings without making them soggy. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame.\nBest for: Wings.\n\n## Spicy Tokyo Steak Marinade\nUse the sauce as the backbone of a fast marinade. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame.\nBest for: Marinades.\n\n## Spicy Tokyo Udon Stir Fry\nFinish hot food with layered flavor. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame.\nBest for: Stir Fry.\n\n## Spicy Tokyo Gyoza Dip\nMake the dip people remember. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame.\nBest for: Dipping Sauces.\n"
  },
  {
    "slug": "how-to-use-noodlebomb-citrus-shoyu",
    "title": "How to Use NoodleBomb Citrus Shoyu",
    "description": "Citrus Shoyu recipe ideas for noodles, rice bowls, wings, marinades, stir fry, and dips.",
    "recipes": [
      "citrus-shoyu-cold-noodle-bowl",
      "citrus-shoyu-salmon-rice-bowl",
      "citrus-shoyu-honey-wings",
      "citrus-shoyu-salmon-marinade",
      "citrus-shoyu-shrimp-stir-fry",
      "citrus-shoyu-spring-roll-dip"
    ],
    "body": "# How to Use NoodleBomb Citrus Shoyu\n\nCitrus Shoyu is the bright bottle: bright citrus, clean shoyu, light heat, and a crisp finish.\n\n## Citrus Shoyu Cold Noodle Bowl\nTurn a plain pack into a real bowl. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish.\nBest for: Ramen.\n\n## Citrus Shoyu Salmon Rice Bowl\nBuild a bowl that tastes planned. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish.\nBest for: Rice Bowls.\n\n## Citrus Shoyu Honey Wings\nCoat crispy wings without making them soggy. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish.\nBest for: Wings.\n\n## Citrus Shoyu Salmon Marinade\nUse the sauce as the backbone of a fast marinade. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish.\nBest for: Marinades.\n\n## Citrus Shoyu Shrimp Stir Fry\nFinish hot food with layered flavor. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish.\nBest for: Stir Fry.\n\n## Citrus Shoyu Spring Roll Dip\nMake the dip people remember. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish.\nBest for: Dipping Sauces.\n"
  },
  {
    "slug": "how-to-use-noodlebomb-shoyu-reserve",
    "title": "How to Use NoodleBomb Shoyu Reserve",
    "description": "Shoyu Reserve recipe ideas for noodles, rice bowls, wings, marinades, stir fry, and dips.",
    "recipes": [
      "shoyu-reserve-mushroom-ramen",
      "shoyu-reserve-mushroom-rice-bowl",
      "shoyu-reserve-black-pepper-wings",
      "shoyu-reserve-pork-chop-marinade",
      "shoyu-reserve-mushroom-stir-fry",
      "shoyu-reserve-steak-dip"
    ],
    "body": "# How to Use NoodleBomb Shoyu Reserve\n\nShoyu Reserve is the finishing and marinade bottle: slow-brewed shoyu depth, mellow salt, and savory finish.\n\n## Shoyu Reserve Mushroom Ramen\nTurn a plain pack into a real bowl. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish.\nBest for: Ramen.\n\n## Shoyu Reserve Mushroom Rice Bowl\nBuild a bowl that tastes planned. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish.\nBest for: Rice Bowls.\n\n## Shoyu Reserve Black Pepper Wings\nCoat crispy wings without making them soggy. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish.\nBest for: Wings.\n\n## Shoyu Reserve Pork Chop Marinade\nUse the sauce as the backbone of a fast marinade. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish.\nBest for: Marinades.\n\n## Shoyu Reserve Mushroom Stir Fry\nFinish hot food with layered flavor. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish.\nBest for: Stir Fry.\n\n## Shoyu Reserve Steak Dip\nMake the dip people remember. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish.\nBest for: Dipping Sauces.\n"
  }
] satisfies RecipeBlogPost[];
export const GENERATED_EMAIL_CAMPAIGNS = [
  {
    "id": "email-original-use-cases",
    "flavorName": "Original",
    "subject": "6 ways to use Original this week",
    "previewText": "Ramen, rice bowls, wings, marinades, stir fry, and dips with Original.",
    "sections": [
      {
        "headline": "Original is not just for ramen.",
        "body": "Use it when dinner needs deep soy, garlic, ginger, sesame, and balanced umami."
      },
      {
        "headline": "Original Weeknight Ramen Bowl",
        "body": "10 min. Turn a plain pack into a real bowl. Original brings deep soy, garlic, ginger, sesame, and balanced umami."
      },
      {
        "headline": "Original Crispy Chicken Rice Bowl",
        "body": "18 min. Build a bowl that tastes planned. Original brings deep soy, garlic, ginger, sesame, and balanced umami."
      },
      {
        "headline": "Original Sticky Sesame Wings",
        "body": "45 min. Coat crispy wings without making them soggy. Original brings deep soy, garlic, ginger, sesame, and balanced umami."
      },
      {
        "headline": "Original Garlic Chicken Marinade",
        "body": "25 min + marinate. Use the sauce as the backbone of a fast marinade. Original brings deep soy, garlic, ginger, sesame, and balanced umami."
      },
      {
        "headline": "Original Broccoli Noodle Stir Fry",
        "body": "15 min. Finish hot food with layered flavor. Original brings deep soy, garlic, ginger, sesame, and balanced umami."
      },
      {
        "headline": "Original Dumpling Dip",
        "body": "3 min. Make the dip people remember. Original brings deep soy, garlic, ginger, sesame, and balanced umami."
      }
    ],
    "ctaLabel": "Shop Original",
    "ctaUrl": "/product/original-ramen"
  },
  {
    "id": "email-spicy-tokyo-use-cases",
    "flavorName": "Spicy Tokyo",
    "subject": "6 ways to use Spicy Tokyo this week",
    "previewText": "Ramen, rice bowls, wings, marinades, stir fry, and dips with Spicy Tokyo.",
    "sections": [
      {
        "headline": "Spicy Tokyo is not just for ramen.",
        "body": "Use it when dinner needs roasted chili heat, dark soy depth, garlic, and sesame."
      },
      {
        "headline": "Spicy Tokyo Fire Ramen",
        "body": "10 min. Turn a plain pack into a real bowl. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame."
      },
      {
        "headline": "Spicy Tokyo Steak Rice Bowl",
        "body": "18 min. Build a bowl that tastes planned. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame."
      },
      {
        "headline": "Spicy Tokyo Chili Wings",
        "body": "45 min. Coat crispy wings without making them soggy. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame."
      },
      {
        "headline": "Spicy Tokyo Steak Marinade",
        "body": "25 min + marinate. Use the sauce as the backbone of a fast marinade. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame."
      },
      {
        "headline": "Spicy Tokyo Udon Stir Fry",
        "body": "15 min. Finish hot food with layered flavor. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame."
      },
      {
        "headline": "Spicy Tokyo Gyoza Dip",
        "body": "3 min. Make the dip people remember. Spicy Tokyo brings roasted chili heat, dark soy depth, garlic, and sesame."
      }
    ],
    "ctaLabel": "Shop Spicy Tokyo",
    "ctaUrl": "/product/spicy-tokyo"
  },
  {
    "id": "email-citrus-shoyu-use-cases",
    "flavorName": "Citrus Shoyu",
    "subject": "6 ways to use Citrus Shoyu this week",
    "previewText": "Ramen, rice bowls, wings, marinades, stir fry, and dips with Citrus Shoyu.",
    "sections": [
      {
        "headline": "Citrus Shoyu is not just for ramen.",
        "body": "Use it when dinner needs bright citrus, clean shoyu, light heat, and a crisp finish."
      },
      {
        "headline": "Citrus Shoyu Cold Noodle Bowl",
        "body": "10 min. Turn a plain pack into a real bowl. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish."
      },
      {
        "headline": "Citrus Shoyu Salmon Rice Bowl",
        "body": "18 min. Build a bowl that tastes planned. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish."
      },
      {
        "headline": "Citrus Shoyu Honey Wings",
        "body": "45 min. Coat crispy wings without making them soggy. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish."
      },
      {
        "headline": "Citrus Shoyu Salmon Marinade",
        "body": "25 min + marinate. Use the sauce as the backbone of a fast marinade. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish."
      },
      {
        "headline": "Citrus Shoyu Shrimp Stir Fry",
        "body": "15 min. Finish hot food with layered flavor. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish."
      },
      {
        "headline": "Citrus Shoyu Spring Roll Dip",
        "body": "3 min. Make the dip people remember. Citrus Shoyu brings bright citrus, clean shoyu, light heat, and a crisp finish."
      }
    ],
    "ctaLabel": "Shop Citrus Shoyu",
    "ctaUrl": "/product/citrus-shoyu"
  },
  {
    "id": "email-shoyu-reserve-use-cases",
    "flavorName": "Shoyu Reserve",
    "subject": "6 ways to use Shoyu Reserve this week",
    "previewText": "Ramen, rice bowls, wings, marinades, stir fry, and dips with Shoyu Reserve.",
    "sections": [
      {
        "headline": "Shoyu Reserve is not just for ramen.",
        "body": "Use it when dinner needs slow-brewed shoyu depth, mellow salt, and savory finish."
      },
      {
        "headline": "Shoyu Reserve Mushroom Ramen",
        "body": "10 min. Turn a plain pack into a real bowl. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish."
      },
      {
        "headline": "Shoyu Reserve Mushroom Rice Bowl",
        "body": "18 min. Build a bowl that tastes planned. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish."
      },
      {
        "headline": "Shoyu Reserve Black Pepper Wings",
        "body": "45 min. Coat crispy wings without making them soggy. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish."
      },
      {
        "headline": "Shoyu Reserve Pork Chop Marinade",
        "body": "25 min + marinate. Use the sauce as the backbone of a fast marinade. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish."
      },
      {
        "headline": "Shoyu Reserve Mushroom Stir Fry",
        "body": "15 min. Finish hot food with layered flavor. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish."
      },
      {
        "headline": "Shoyu Reserve Steak Dip",
        "body": "3 min. Make the dip people remember. Shoyu Reserve brings slow-brewed shoyu depth, mellow salt, and savory finish."
      }
    ],
    "ctaLabel": "Shop Shoyu Reserve",
    "ctaUrl": "/product/shoyu-reserve"
  }
] satisfies RecipeEmailCampaign[];
