import { motion } from "framer-motion";
import { ArrowRight, Package, ShieldCheck, Truck } from "lucide-react";

const products = [
  { name: "Original Shoyu", sku: "NB-OG-001", size: "12 fl oz (354ml)", msrp: "$11.99", wholesale: "$5.75", moq: "12 units", shelfLife: "18 months", support: "Full POS assets" },
    { name: "Spicy Tokyo", sku: "NB-ST-002", size: "12 fl oz (354ml)", msrp: "$11.99", wholesale: "$5.75", moq: "12 units", shelfLife: "18 months", support: "Full POS assets" },
      { name: "Ryu Garlic", sku: "NB-RG-003", size: "12 fl oz (354ml)", msrp: "$11.99", wholesale: "$5.75", moq: "12 units", shelfLife: "18 months", support: "Full POS assets" },
        { name: "Citrus Shoyu", sku: "NB-CS-004", size: "12 fl oz (354ml)", msrp: "$11.99", wholesale: "$5.75", moq: "12 units", shelfLife: "18 months", support: "Full POS assets" },
        ];

        const specRows = [
          { label: "Size", key: "size" },
            { label: "MSRP", key: "msrp" },
              { label: "Wholesale", key: "wholesale" },
                { label: "MOQ", key: "moq" },
                  { label: "Shelf life", key: "shelfLife" },
                    { label: "Support", key: "support" },
                    ];

                    const Wholesale = () => {
                      return (
                          <div className="min-h-screen bg-background text-foreground">
                                {/* Hero */}
                                      <section className="py-20 px-4 text-center bg-gradient-to-b from-zinc-900 to-background">
                                              <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
                                                        <h1 className="text-4xl md:text-6xl font-bold mb-4">
                                                                    Wholesale <span className="text-primary">Program</span>
                                                                              </h1>
                                                                                        <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-8">
                                                                                                    Bring NoodleBomb to your shelves. Premium ramen sauces with retail margins that make sense.
                                                                                                              </p>
                                                                                                                        <a href="mailto:wholesale@noodlebomb.com" className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-8 py-3 rounded-full font-semibold hover:opacity-90 transition">
                                                                                                                                    Apply Now <ArrowRight className="w-4 h-4" />
                                                                                                                                              </a>
                                                                                                                                                      </motion.div>
                                                                                                                                                            </section>

                                                                                                                                                                  {/* Product Specs Table */}
                                                                                                                                                                        <section className="py-16 px-4 max-w-5xl mx-auto">
                                                                                                                                                                                <h2 className="text-2xl md:text-3xl font-bold mb-8 text-center">Product Specifications</h2>
                                                                                                                                                                                        <div className="overflow-x-auto rounded-xl border border-zinc-700">
                                                                                                                                                                                                  <table className="w-full text-sm">
                                                                                                                                                                                                              <thead>
                                                                                                                                                                                                                            <tr className="bg-zinc-950 border-b border-zinc-700">
                                                                                                                                                                                                                                            <th className="text-left px-5 py-3 text-white font-semibold w-32">Spec</th>
                                                                                                                                                                                                                                                            {products.map((p) => (
                                                                                                                                                                                                                                                                              <th key={p.sku} className="text-left px-5 py-3 text-white font-semibold">{p.name}</th>
                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                        </thead>
                                                                                                                                                                                                                                                                                                                                    <tbody>
                                                                                                                                                                                                                                                                                                                                                  {specRows.map((row, i) => (
                                                                                                                                                                                                                                                                                                                                                                  <tr key={row.key} className={i % 2 === 0 ? "bg-zinc-800 text-white" : "bg-zinc-900 text-white"}>
                                                                                                                                                                                                                                                                                                                                                                                    <td className="px-5 py-3 font-medium text-white">{row.label}</td>
                                                                                                                                                                                                                                                                                                                                                                                                      {products.map((p) => (
                                                                                                                                                                                                                                                                                                                                                                                                                          <td key={p.sku} className="px-5 py-3 text-white">{p[row.key as keyof typeof p]}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Why NoodleBomb */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <section className="py-16 px-4 max-w-5xl mx-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2 className="text-2xl md:text-3xl font-bold mb-10 text-center">Why Carry NoodleBomb?</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="grid md:grid-cols-3 gap-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { icon: <Package className="w-8 h-8 text-primary" />, title: "Shelf-Ready Packaging", body: "Clean labels, premium design, and standout branding that sells itself." },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { icon: <ShieldCheck className="w-8 h-8 text-primary" />, title: "18-Month Shelf Life", body: "No refrigeration required until opened. Minimal shrink risk." },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { icon: <Truck className="w-8 h-8 text-primary" />, title: "Fast Fulfillment", body: "Orders ship within 3 business days. EDI available for larger accounts." },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ].map((card) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={card.title} className="bg-zinc-900 rounded-xl p-6 border border-zinc-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mb-3">{card.icon}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="font-bold text-white mb-2">{card.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-zinc-300 text-sm">{card.body}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* CTA */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <section className="py-16 px-4 text-center bg-zinc-900">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-2xl md:text-3xl font-bold mb-4">Ready to Stock NoodleBomb?</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-muted-foreground mb-8 max-w-lg mx-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Fill out our wholesale inquiry and we will respond within 1 business day.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <a href="mailto:wholesale@noodlebomb.com" className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-8 py-3 rounded-full font-semibold hover:opacity-90 transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Get in Touch <ArrowRight className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default Wholesale;